namespace OnboardingDiary.Api.Domain;

public class TaskEntry
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public User? User { get; set; }

    public DateOnly EntryDate { get; set; }

    public required string Title { get; set; }

    public string? Description { get; set; }

    public TaskCategory Category { get; set; } = TaskCategory.Other;

    public TaskEntryStatus Status { get; set; } = TaskEntryStatus.Todo;

    public TaskPriority Priority { get; set; } = TaskPriority.Medium;

    /// <summary>Set when the task was generated by applying a checklist template.</summary>
    public int? ChecklistAssignmentId { get; set; }

    public ChecklistAssignment? ChecklistAssignment { get; set; }

    /// <summary>Provenance only — the template item may later be edited or removed.</summary>
    public int? ChecklistItemId { get; set; }

    /// <summary>Set while the status is Done, cleared when the task is reopened.</summary>
    public DateTimeOffset? CompletedAt { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }
}
