import { Router } from 'express';
import PDFDocument from 'pdfkit';
import { z } from 'zod';
import type { AuthedRequest } from '../lib/auth.js';
import { requireAuth, visibleUserIds } from '../lib/auth.js';
import { ENTITIES } from '../lib/entities.js';
import type { EntryRow } from '../lib/queries.js';
import { listEntries } from '../lib/queries.js';
import type { EntityName } from '../lib/types.js';

export const reportsRouter = Router();

reportsRouter.use(requireAuth);

const querySchema = z.object({
  type: z.enum(['tasks', 'issues', 'feedback', 'combined']).default('combined'),
  format: z.enum(['csv', 'pdf', 'json']).default('json'),
  from: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Please choose a start date'),
  to: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Please choose an end date'),
  userId: z.coerce.number().int().positive().optional(),
});

const sectionsFor = (type: string): ReadonlyArray<EntityName> =>
  type === 'combined' ? ['tasks', 'issues', 'feedback', 'notes'] : [type as EntityName];

const csvCell = (value: unknown): string => {
  const text = value === null || value === undefined ? '' : String(value);
  return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
};

const toCsv = (sections: ReadonlyArray<[EntityName, EntryRow[]]>): string => {
  const lines: string[] = [];
  for (const [name, rows] of sections) {
    const entity = ENTITIES[name];
    const headers = ['category', 'recruit', ...entity.columns];
    lines.push(headers.map(csvCell).join(','));
    for (const row of rows) {
      lines.push(
        [name, row.userName, ...entity.columns.map((column) => row[column])].map(csvCell).join(','),
      );
    }
    lines.push('');
  }
  return lines.join('\n');
};

reportsRouter.get('/', (req: AuthedRequest, res) => {
  const actor = req.user;
  if (!actor) {
    res.status(401).json({ error: 'Authentication required' });
    return;
  }
  const parsed = querySchema.safeParse(req.query);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.issues[0]?.message ?? 'Please check the filters' });
    return;
  }
  const { type, format, from, to, userId } = parsed.data;
  if (from > to) {
    res.status(400).json({ error: 'Please choose an end date on or after the start date' });
    return;
  }
  const allowed = visibleUserIds(actor);
  if (userId !== undefined && !allowed.includes(userId)) {
    res.status(403).json({ error: 'You cannot report on this recruit' });
    return;
  }
  const userIds = userId === undefined ? allowed : [userId];
  const sections = sectionsFor(type).map(
    (name) =>
      [name, listEntries(ENTITIES[name], { userIds, from, to })] as [EntityName, EntryRow[]],
  );
  const stamp = `${from}_to_${to}`;

  if (format === 'csv') {
    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${type}-report-${stamp}.csv"`);
    res.send(toCsv(sections));
    return;
  }

  if (format === 'pdf') {
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${type}-report-${stamp}.pdf"`);
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    doc.pipe(res);
    doc.fillColor('#202842').fontSize(20).text('Onboarding Diary Report');
    doc
      .moveDown(0.3)
      .fillColor('#5D698D')
      .fontSize(12)
      .text(`${type} · ${from} to ${to} · generated by ${actor.name}`);
    for (const [name, rows] of sections) {
      const entity = ENTITIES[name];
      doc
        .moveDown(1)
        .fillColor('#3457DC')
        .fontSize(16)
        .text(`${entity.label} entries (${rows.length})`);
      if (rows.length === 0) {
        doc.moveDown(0.2).fillColor('#5D698D').fontSize(12).text('No entries in this period.');
      }
      for (const row of rows) {
        const heading = String(row.title ?? row.subject ?? '');
        doc
          .moveDown(0.4)
          .fillColor('#202842')
          .fontSize(12)
          .text(`${String(row.date)} — ${heading} (${String(row.userName)})`);
        const details = entity.columns
          .filter((column) => column !== 'date' && column !== 'title' && column !== 'subject')
          .map((column) => `${column}: ${String(row[column] ?? '')}`)
          .join(' · ');
        doc.fillColor('#5D698D').fontSize(10).text(details);
      }
    }
    doc.end();
    return;
  }

  res.json({ type, from, to, sections: Object.fromEntries(sections) });
});
