CREATE TABLE users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                 VARCHAR(255)             NOT NULL,
    password_hash         VARCHAR(100)             NOT NULL,
    enabled               BOOLEAN                  NOT NULL DEFAULT TRUE,
    must_change_password  BOOLEAN                  NOT NULL DEFAULT FALSE,
    failed_login_attempts INT                      NOT NULL DEFAULT 0,
    locked_until          TIMESTAMP WITH TIME ZONE,
    last_login_at         TIMESTAMP WITH TIME ZONE,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    version               INT                      NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE user_roles (
    user_id BIGINT      NOT NULL,
    role    VARCHAR(20) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_user_roles_role CHECK (role IN ('RECRUIT', 'MANAGER', 'ADMIN'))
);

CREATE TABLE profiles (
    user_id    BIGINT PRIMARY KEY,
    full_name  VARCHAR(120)             NOT NULL,
    job_title  VARCHAR(120),
    department VARCHAR(120)             NOT NULL,
    start_date DATE                     NOT NULL,
    manager_id BIGINT,
    phone      VARCHAR(30),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version    INT                      NOT NULL DEFAULT 0,
    CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_profiles_manager FOREIGN KEY (manager_id) REFERENCES users (id)
);

CREATE INDEX ix_profiles_manager ON profiles (manager_id);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL,
    token_hash VARCHAR(100)             NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked    BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX ix_refresh_tokens_user ON refresh_tokens (user_id);

CREATE TABLE audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id       BIGINT,
    action         VARCHAR(50)              NOT NULL,
    target_user_id BIGINT,
    details        VARCHAR(4000),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_audit_log_actor FOREIGN KEY (actor_id) REFERENCES users (id),
    CONSTRAINT fk_audit_log_target FOREIGN KEY (target_user_id) REFERENCES users (id)
);

CREATE INDEX ix_audit_log_created_at ON audit_log (created_at);
