CREATE TABLE tasks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id     BIGINT                   NOT NULL,
    entry_date   DATE                     NOT NULL,
    title        VARCHAR(150)             NOT NULL,
    description  VARCHAR(5000),
    category     VARCHAR(30)              NOT NULL,
    status       VARCHAR(20)              NOT NULL,
    priority     VARCHAR(10)              NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    version      INT                      NOT NULL DEFAULT 0,
    CONSTRAINT fk_tasks_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT ck_tasks_category CHECK (category IN ('TRAINING', 'SETUP', 'DOCUMENTATION', 'MEETING',
                                                     'CODING', 'SHADOWING', 'ADMINISTRATIVE', 'OTHER')),
    CONSTRAINT ck_tasks_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED')),
    CONSTRAINT ck_tasks_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE INDEX ix_tasks_owner_date ON tasks (owner_id, entry_date);

CREATE TABLE issues (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id         BIGINT                   NOT NULL,
    related_task_id  BIGINT,
    entry_date       DATE                     NOT NULL,
    title            VARCHAR(150)             NOT NULL,
    description      VARCHAR(5000),
    severity         VARCHAR(10)              NOT NULL,
    status           VARCHAR(20)              NOT NULL,
    resolution_notes VARCHAR(5000),
    resolved_at      TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    version          INT                      NOT NULL DEFAULT 0,
    CONSTRAINT fk_issues_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_issues_task FOREIGN KEY (related_task_id) REFERENCES tasks (id) ON DELETE SET NULL,
    CONSTRAINT ck_issues_severity CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_issues_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'))
);

CREATE INDEX ix_issues_owner_date ON issues (owner_id, entry_date);
CREATE INDEX ix_issues_related_task ON issues (related_task_id);

CREATE TABLE feedback (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT                   NOT NULL,
    entry_date DATE                     NOT NULL,
    subject    VARCHAR(150)             NOT NULL,
    type       VARCHAR(20)              NOT NULL,
    details    VARCHAR(5000)            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version    INT                      NOT NULL DEFAULT 0,
    CONSTRAINT fk_feedback_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT ck_feedback_type CHECK (type IN ('POSITIVE', 'SUGGESTION', 'CONCERN'))
);

CREATE INDEX ix_feedback_owner_date ON feedback (owner_id, entry_date);

CREATE TABLE notes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT                   NOT NULL,
    entry_date DATE                     NOT NULL,
    title      VARCHAR(150)             NOT NULL,
    content    VARCHAR(20000)           NOT NULL,
    shared     BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version    INT                      NOT NULL DEFAULT 0,
    CONSTRAINT fk_notes_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX ix_notes_owner_date ON notes (owner_id, entry_date);

CREATE TABLE note_tags (
    note_id BIGINT      NOT NULL,
    tag     VARCHAR(40) NOT NULL,
    CONSTRAINT pk_note_tags PRIMARY KEY (note_id, tag),
    CONSTRAINT fk_note_tags_note FOREIGN KEY (note_id) REFERENCES notes (id) ON DELETE CASCADE
);

CREATE INDEX ix_note_tags_tag ON note_tags (tag);
