CREATE TABLE checklist_templates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120)             NOT NULL,
    description VARCHAR(1000),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    version     INT                      NOT NULL DEFAULT 0,
    CONSTRAINT uq_checklist_templates_name UNIQUE (name)
);

CREATE TABLE checklist_template_items (
    template_id    BIGINT        NOT NULL,
    sort_order     INT           NOT NULL,
    title          VARCHAR(200)  NOT NULL,
    description    VARCHAR(1000),
    due_day_offset INT,
    CONSTRAINT pk_checklist_template_items PRIMARY KEY (template_id, sort_order),
    CONSTRAINT fk_checklist_template_items_template FOREIGN KEY (template_id)
        REFERENCES checklist_templates (id) ON DELETE CASCADE
);

CREATE TABLE checklist_assignments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recruit_id  BIGINT                   NOT NULL,
    template_id BIGINT,
    name        VARCHAR(120)             NOT NULL,
    assigned_by BIGINT                   NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    version     INT                      NOT NULL DEFAULT 0,
    CONSTRAINT fk_checklist_assignments_recruit FOREIGN KEY (recruit_id) REFERENCES users (id),
    CONSTRAINT fk_checklist_assignments_template FOREIGN KEY (template_id)
        REFERENCES checklist_templates (id) ON DELETE SET NULL,
    CONSTRAINT fk_checklist_assignments_assigned_by FOREIGN KEY (assigned_by) REFERENCES users (id),
    CONSTRAINT uq_checklist_assignments_recruit_template UNIQUE (recruit_id, template_id)
);

CREATE INDEX ix_checklist_assignments_recruit ON checklist_assignments (recruit_id);

CREATE TABLE checklist_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT                   NOT NULL,
    sort_order    INT                      NOT NULL,
    title         VARCHAR(200)             NOT NULL,
    description   VARCHAR(1000),
    due_date      DATE,
    completed_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_checklist_items_assignment FOREIGN KEY (assignment_id)
        REFERENCES checklist_assignments (id) ON DELETE CASCADE
);

CREATE INDEX ix_checklist_items_assignment ON checklist_items (assignment_id);
