import PDFDocument from 'pdfkit';
import type { ReportData } from './reports.service.js';

/**
 * Renders a report to a PDF buffer (docs/ASSUMPTIONS.md §11). Content mirrors the
 * on-screen report: a header, a summary block, then a section per entry type.
 */
export function pdfFromReport(report: ReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).text('Onboarding Diary — Report', { align: 'left' });
    doc.moveDown(0.3);
    doc
      .fontSize(10)
      .fillColor('#555')
      .text(`Range: ${report.meta.start} to ${report.meta.end}`)
      .text(`Scope: ${report.meta.scope}`)
      .text(`Generated by ${report.meta.generatedBy} on ${report.meta.generatedAt}`);
    doc.fillColor('#000').moveDown();

    doc.fontSize(14).text('Summary');
    doc.moveDown(0.2);
    doc
      .fontSize(10)
      .text(`Tasks: ${report.summary.taskTotal} (completed ${report.summary.taskCompleted})`)
      .text(`Issues: ${report.summary.issueTotal} (open ${report.summary.issueOpen})`)
      .text(`Feedback: ${report.summary.feedbackTotal}`)
      .text(`Notes: ${report.summary.noteTotal}`);
    doc.moveDown();

    section(doc, 'Tasks', report.tasks, (t) => [
      `${t.date} — ${t.title} [${t.status}/${t.priority}]`,
      `Category: ${t.category} · Owner: ${t.owner}`,
      t.description,
    ]);
    section(doc, 'Issues', report.issues, (i) => [
      `${i.date} — ${i.title} [${i.status}/${i.severity}]`,
      `Owner: ${i.owner}`,
      i.description,
      i.resolutionNotes ? `Resolution: ${i.resolutionNotes}` : '',
    ]);
    section(doc, 'Feedback', report.feedback, (f) => [
      `${f.date} — ${f.subject} [${f.type}]`,
      `Owner: ${f.owner}`,
      f.details,
    ]);
    section(doc, 'Notes', report.notes, (n) => [
      `${n.date} — ${n.title}`,
      `Owner: ${n.owner}${n.tags ? ` · Tags: ${n.tags}` : ''}`,
      n.content,
    ]);

    doc.end();
  });
}

function section<T>(
  doc: PDFKit.PDFDocument,
  title: string,
  rows: T[],
  lines: (row: T) => string[],
): void {
  doc.fontSize(14).text(`${title} (${rows.length})`);
  doc.moveDown(0.2);
  if (rows.length === 0) {
    doc.fontSize(10).fillColor('#888').text('No entries in range.').fillColor('#000');
    doc.moveDown();
    return;
  }
  for (const row of rows) {
    for (const line of lines(row).filter(Boolean)) {
      doc.fontSize(10).text(line);
    }
    doc.moveDown(0.4);
  }
  doc.moveDown(0.4);
}
