export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;

export const USER = {
  NAME_MIN_LENGTH: 1,
  NAME_MAX_LENGTH: 100,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
  EMAIL_MAX_LENGTH: 255,
  BIO_MAX_LENGTH: 500,
  DEPARTMENT_MAX_LENGTH: 100,
  POSITION_MAX_LENGTH: 200,
} as const;

export const TASK = {
  TITLE_MIN_LENGTH: 3,
  TITLE_MAX_LENGTH: 255,
  DESCRIPTION_MAX_LENGTH: 50_000,
  MAX_TAGS: 10,
  TAG_MAX_LENGTH: 50,
} as const;

export const ISSUE = {
  TITLE_MIN_LENGTH: 3,
  TITLE_MAX_LENGTH: 255,
  DESCRIPTION_MIN_LENGTH: 10,
  DESCRIPTION_MAX_LENGTH: 50_000,
  RESOLUTION_MAX_LENGTH: 10_000,
  MAX_TAGS: 10,
  TAG_MAX_LENGTH: 50,
} as const;

export const NOTE = {
  TITLE_MIN_LENGTH: 3,
  TITLE_MAX_LENGTH: 255,
  BODY_MIN_LENGTH: 10,
  BODY_MAX_LENGTH: 50_000,
  MOOD_MIN: 1,
  MOOD_MAX: 5,
  MAX_TAGS: 10,
  TAG_MAX_LENGTH: 50,
} as const;

export const FEEDBACK = {
  TITLE_MIN_LENGTH: 3,
  TITLE_MAX_LENGTH: 255,
  BODY_MIN_LENGTH: 10,
  BODY_MAX_LENGTH: 10_000,
  RATING_MIN: 1,
  RATING_MAX: 5,
} as const;

export const REPORT = {
  TITLE_MIN_LENGTH: 3,
  TITLE_MAX_LENGTH: 255,
  SUMMARY_MAX_LENGTH: 50_000,
} as const;
