export enum Role {
  RECRUIT = 'RECRUIT',
  MENTOR = 'MENTOR',
  MANAGER = 'MANAGER',
  HR_ADMIN = 'HR_ADMIN',
  SYS_ADMIN = 'SYS_ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  INVITED = 'INVITED',
}

export enum Visibility {
  PRIVATE = 'PRIVATE',
  MENTOR_ONLY = 'MENTOR_ONLY',
  TEAM = 'TEAM',
  PUBLIC = 'PUBLIC',
}

export enum MilestoneCategory {
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  TECHNICAL = 'TECHNICAL',
  SOCIAL = 'SOCIAL',
  LEARNING = 'LEARNING',
  DELIVERABLE = 'DELIVERABLE',
}

export enum EnrollmentStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum CompletionStatus {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum NotificationType {
  COMMENT_ADDED = 'COMMENT_ADDED',
  MILESTONE_REMINDER = 'MILESTONE_REMINDER',
  MILESTONE_VERIFIED = 'MILESTONE_VERIFIED',
  MILESTONE_REJECTED = 'MILESTONE_REJECTED',
  MENTOR_ASSIGNED = 'MENTOR_ASSIGNED',
  PROGRAM_ENROLLED = 'PROGRAM_ENROLLED',
}
