dependencies {
    implementation project(':common')
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.flywaydb:flyway-core'
    runtimeOnly 'org.xerial:sqlite-jdbc:3.45.3.0'
    implementation 'org.hibernate.orm:hibernate-community-dialects:6.4.4.Final'
    implementation 'com.github.librepdf:openpdf:2.0.2'
    implementation 'com.opencsv:opencsv:5.9'
}
