using System.Globalization;
using CsvHelper;
using CsvHelper.Configuration;
using OnboardingDiary.Application.Reports;
using OnboardingDiary.Domain.Enums;

namespace OnboardingDiary.Infrastructure.Reports;

public class CsvReportRenderer : IReportRenderer
{
    public ReportFormat Format => ReportFormat.Csv;

    public byte[] Render(ReportData data)
    {
        using var memoryStream = new MemoryStream();
        using var writer = new StreamWriter(memoryStream);
        using var csv = new CsvWriter(writer, new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            HasHeaderRecord = true
        });

        csv.WriteField("Onboarding Diary Report");
        csv.NextRecord();
        csv.WriteField($"Recruit: {data.RecruitName}");
        csv.NextRecord();
        csv.WriteField($"Department: {data.Department}");
        csv.NextRecord();
        csv.WriteField($"Period: {data.ReportStartDate:yyyy-MM-dd} to {data.ReportEndDate:yyyy-MM-dd}");
        csv.NextRecord();
        csv.WriteField($"Generated by: {data.GeneratedByName}");
        csv.NextRecord();
        csv.WriteField($"Generated on: {data.GeneratedOn:yyyy-MM-dd HH:mm} UTC");
        csv.NextRecord();
        csv.NextRecord();

        if (data.Categories.Contains("tasks"))
        {
            csv.WriteField("=== Tasks ===");
            csv.NextRecord();
            csv.WriteField("Date");
            csv.WriteField("Title");
            csv.WriteField("Description");
            csv.WriteField("Category");
            csv.WriteField("Status");
            csv.WriteField("Priority");
            csv.WriteField("CompletedAt");
            csv.NextRecord();

            foreach (var task in data.Tasks)
            {
                csv.WriteField(task.Date.ToString("yyyy-MM-dd"));
                csv.WriteField(task.Title);
                csv.WriteField(task.Description ?? "");
                csv.WriteField(task.Category.ToString());
                csv.WriteField(task.Status.ToString());
                csv.WriteField(task.Priority.ToString());
                csv.WriteField(task.CompletedAt?.ToString("yyyy-MM-dd HH:mm") ?? "");
                csv.NextRecord();
            }

            csv.NextRecord();
        }

        if (data.Categories.Contains("issues"))
        {
            csv.WriteField("=== Issues ===");
            csv.NextRecord();
            csv.WriteField("Date");
            csv.WriteField("Title");
            csv.WriteField("Description");
            csv.WriteField("Severity");
            csv.WriteField("Status");
            csv.WriteField("ResolutionNotes");
            csv.WriteField("IsEscalated");
            csv.NextRecord();

            foreach (var issue in data.Issues)
            {
                csv.WriteField(issue.Date.ToString("yyyy-MM-dd"));
                csv.WriteField(issue.Title);
                csv.WriteField(issue.Description);
                csv.WriteField(issue.Severity.ToString());
                csv.WriteField(issue.Status.ToString());
                csv.WriteField(issue.ResolutionNotes ?? "");
                csv.WriteField(issue.IsEscalated ? "Yes" : "No");
                csv.NextRecord();
            }

            csv.NextRecord();
        }

        if (data.Categories.Contains("feedback"))
        {
            csv.WriteField("=== Feedback ===");
            csv.NextRecord();
            csv.WriteField("Date");
            csv.WriteField("Subject");
            csv.WriteField("Type");
            csv.WriteField("Details");
            csv.NextRecord();

            foreach (var fb in data.Feedbacks)
            {
                csv.WriteField(fb.Date.ToString("yyyy-MM-dd"));
                csv.WriteField(fb.Subject);
                csv.WriteField(fb.Type.ToString());
                csv.WriteField(fb.Details);
                csv.NextRecord();
            }

            csv.NextRecord();
        }

        if (data.Categories.Contains("notes"))
        {
            csv.WriteField("=== Notes ===");
            csv.NextRecord();
            csv.WriteField("Date");
            csv.WriteField("Title");
            csv.WriteField("Content");
            csv.WriteField("Tags");
            csv.WriteField("IsPinned");
            csv.NextRecord();

            foreach (var note in data.Notes)
            {
                csv.WriteField(note.Date.ToString("yyyy-MM-dd"));
                csv.WriteField(note.Title);
                csv.WriteField(note.Content);
                csv.WriteField(string.Join("; ", note.Tags));
                csv.WriteField(note.IsPinned ? "Yes" : "No");
                csv.NextRecord();
            }

            csv.NextRecord();
        }

        writer.Flush();
        return memoryStream.ToArray();
    }
}
