using OnboardingDiary.Application.Reports;
using OnboardingDiary.Domain.Enums;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace OnboardingDiary.Infrastructure.Reports;

public class PdfReportRenderer : IReportRenderer
{
    public ReportFormat Format => ReportFormat.Pdf;

    public byte[] Render(ReportData data)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Column(col =>
                {
                    col.Item().Text("Onboarding Diary Report").Bold().FontSize(18);
                    col.Item().PaddingTop(8).Text(txt =>
                    {
                        txt.Span("Recruit: ").Bold();
                        txt.Span(data.RecruitName);
                    });
                    col.Item().Text(txt =>
                    {
                        txt.Span("Department: ").Bold();
                        txt.Span(data.Department);
                    });
                    col.Item().Text(txt =>
                    {
                        txt.Span("Period: ").Bold();
                        txt.Span($"{data.ReportStartDate:yyyy-MM-dd} to {data.ReportEndDate:yyyy-MM-dd}");
                    });
                    col.Item().Text(txt =>
                    {
                        txt.Span("Generated by: ").Bold();
                        txt.Span(data.GeneratedByName);
                    });
                    col.Item().Text(txt =>
                    {
                        txt.Span("Generated on: ").Bold();
                        txt.Span(data.GeneratedOn.ToString("yyyy-MM-dd HH:mm UTC"));
                    });
                    col.Item().PaddingTop(10).LineHorizontal(1).LineColor(Colors.Grey.Medium);
                });

                page.Content().PaddingTop(10).Column(col =>
                {
                    if (data.Categories.Contains("tasks") && data.Tasks.Count > 0)
                    {
                        col.Item().PaddingTop(10).Text("Tasks").Bold().FontSize(14);
                        col.Item().PaddingTop(5).Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(4);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(2);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Text("Date").Bold();
                                header.Cell().Text("Title").Bold();
                                header.Cell().Text("Category").Bold();
                                header.Cell().Text("Status").Bold();
                                header.Cell().Text("Priority").Bold();
                            });

                            foreach (var task in data.Tasks)
                            {
                                table.Cell().Text(task.Date.ToString("yyyy-MM-dd"));
                                table.Cell().Text(task.Title);
                                table.Cell().Text(task.Category.ToString());
                                table.Cell().Text(task.Status.ToString());
                                table.Cell().Text(task.Priority.ToString());
                            }
                        });
                    }

                    if (data.Categories.Contains("issues") && data.Issues.Count > 0)
                    {
                        col.Item().PaddingTop(10).Text("Issues").Bold().FontSize(14);
                        col.Item().PaddingTop(5).Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(4);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(2);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Text("Date").Bold();
                                header.Cell().Text("Title").Bold();
                                header.Cell().Text("Severity").Bold();
                                header.Cell().Text("Status").Bold();
                                header.Cell().Text("Escalated").Bold();
                            });

                            foreach (var issue in data.Issues)
                            {
                                table.Cell().Text(issue.Date.ToString("yyyy-MM-dd"));
                                table.Cell().Text(issue.Title);
                                table.Cell().Text(issue.Severity.ToString());
                                table.Cell().Text(issue.Status.ToString());
                                table.Cell().Text(issue.IsEscalated ? "Yes" : "No");
                            }
                        });
                    }

                    if (data.Categories.Contains("feedback") && data.Feedbacks.Count > 0)
                    {
                        col.Item().PaddingTop(10).Text("Feedback").Bold().FontSize(14);
                        col.Item().PaddingTop(5).Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(4);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(4);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Text("Date").Bold();
                                header.Cell().Text("Subject").Bold();
                                header.Cell().Text("Type").Bold();
                                header.Cell().Text("Details").Bold();
                            });

                            foreach (var fb in data.Feedbacks)
                            {
                                table.Cell().Text(fb.Date.ToString("yyyy-MM-dd"));
                                table.Cell().Text(fb.Subject);
                                table.Cell().Text(fb.Type.ToString());
                                table.Cell().Text(fb.Details.Length > 100 ? fb.Details[..100] + "..." : fb.Details);
                            }
                        });
                    }

                    if (data.Categories.Contains("notes") && data.Notes.Count > 0)
                    {
                        col.Item().PaddingTop(10).Text("Notes").Bold().FontSize(14);
                        col.Item().PaddingTop(5).Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(4);
                                columns.RelativeColumn(4);
                                columns.RelativeColumn(2);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Text("Date").Bold();
                                header.Cell().Text("Title").Bold();
                                header.Cell().Text("Content").Bold();
                                header.Cell().Text("Tags").Bold();
                            });

                            foreach (var note in data.Notes)
                            {
                                table.Cell().Text(note.Date.ToString("yyyy-MM-dd"));
                                table.Cell().Text(note.Title);
                                table.Cell().Text(note.Content.Length > 100 ? note.Content[..100] + "..." : note.Content);
                                table.Cell().Text(string.Join(", ", note.Tags));
                            }
                        });
                    }

                    if (!data.Tasks.Any() && !data.Issues.Any() && !data.Feedbacks.Any() && !data.Notes.Any())
                    {
                        col.Item().PaddingTop(20).Text("No data found for the selected categories and date range.")
                            .Italic().FontColor(Colors.Grey.Medium);
                    }
                });

                page.Footer().AlignCenter().Text(txt =>
                {
                    txt.Span("Page ");
                    txt.CurrentPageNumber();
                    txt.Span(" of ");
                    txt.TotalPages();
                });
            });
        });

        return document.GeneratePdf();
    }
}
