-- Phase 1 foundational schema: department lookup and users.
-- Kept to portable ANSI SQL so it runs on PostgreSQL and on H2 in PostgreSQL mode.

CREATE TABLE department (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50)  NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_department_name UNIQUE (name)
);

CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    department_id BIGINT       NOT NULL,
    start_date    DATE         NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('NEW_RECRUIT', 'MANAGER', 'ADMIN')),
    CONSTRAINT fk_users_department FOREIGN KEY (department_id) REFERENCES department (id)
);

CREATE INDEX ix_users_department_id ON users (department_id);
