-- Admin-maintained task category lookup (REQUIREMENTS 2.6 / US-A04).
-- Portable ANSI SQL so the same migration runs on PostgreSQL and on H2 in PostgreSQL mode.

CREATE TABLE task_category (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) NOT NULL,
    active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_task_category_name UNIQUE (name)
);
