-- Task Log and Issue Log entries (REQUIREMENTS 2.2, 2.3).

CREATE TABLE task_entry (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT        NOT NULL,
    entry_date  DATE          NOT NULL,
    title       VARCHAR(150)  NOT NULL,
    description VARCHAR(5000),
    category_id BIGINT        NOT NULL,
    status      VARCHAR(20)   NOT NULL,
    priority    VARCHAR(10)   NOT NULL,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_task_entry_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_task_entry_category FOREIGN KEY (category_id) REFERENCES task_category (id),
    CONSTRAINT ck_task_entry_status CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED')),
    CONSTRAINT ck_task_entry_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE INDEX ix_task_entry_owner_id ON task_entry (owner_id);
CREATE INDEX ix_task_entry_category_id ON task_entry (category_id);

CREATE TABLE issue_entry (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id         BIGINT       NOT NULL,
    entry_date       DATE         NOT NULL,
    title            VARCHAR(150) NOT NULL,
    description      VARCHAR(5000),
    severity         VARCHAR(10)  NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    resolution_notes VARCHAR(5000),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_issue_entry_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT ck_issue_entry_severity CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_issue_entry_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'))
);

CREATE INDEX ix_issue_entry_owner_id ON issue_entry (owner_id);
