-- Manager-to-recruit oversight (REQUIREMENTS 2.8). Phase 3 uses this table read-only:
-- the admin endpoints that create and remove assignments (section 4.8) are a later phase.

CREATE TABLE manager_assignment (
    id          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id  BIGINT    NOT NULL,
    recruit_id  BIGINT    NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_manager_assignment UNIQUE (manager_id, recruit_id),
    CONSTRAINT fk_manager_assignment_manager FOREIGN KEY (manager_id) REFERENCES users (id),
    CONSTRAINT fk_manager_assignment_recruit FOREIGN KEY (recruit_id) REFERENCES users (id)
);

CREATE INDEX ix_manager_assignment_manager_id ON manager_assignment (manager_id);
CREATE INDEX ix_manager_assignment_recruit_id ON manager_assignment (recruit_id);
