-- Feedback Notes and Additional Notes with tags (REQUIREMENTS 2.4, 2.5).

CREATE TABLE feedback_note (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT       NOT NULL,
    entry_date DATE         NOT NULL,
    subject    VARCHAR(150) NOT NULL,
    type       VARCHAR(20)  NOT NULL,
    details    VARCHAR(5000) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_feedback_note_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT ck_feedback_note_type CHECK (type IN ('POSITIVE', 'SUGGESTION', 'CONCERN'))
);

CREATE INDEX ix_feedback_note_owner_id ON feedback_note (owner_id);

CREATE TABLE additional_note (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT        NOT NULL,
    entry_date DATE          NOT NULL,
    title      VARCHAR(150)  NOT NULL,
    content    VARCHAR(10000) NOT NULL,
    created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_additional_note_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX ix_additional_note_owner_id ON additional_note (owner_id);

-- Tags are stored normalised (trimmed, lower-cased, de-duplicated) by the service layer.
CREATE TABLE note_tag (
    note_id BIGINT      NOT NULL,
    tag     VARCHAR(30) NOT NULL,
    CONSTRAINT pk_note_tag PRIMARY KEY (note_id, tag),
    CONSTRAINT fk_note_tag_note FOREIGN KEY (note_id) REFERENCES additional_note (id) ON DELETE CASCADE
);

CREATE INDEX ix_note_tag_tag ON note_tag (tag);
